### ISSUE TITLE
Google API Key - Sicherheit erhöhen?

### ISSUE THREAD

**Issue by ottosax** [McAtze/-XT-Membermap#12]
Der API-Key ist im Quelltext der Mitgliederkarte für jeden im Browser kopierbar da im Klartext zu sehen.
Eventuell eine Lösung wie hier auf Xenforo.com hier geschrieben?
https://xenforo.com/community/threads/xt-membermap.193479/post-1512863

**Comment by McAtze** [comment]
Ich habe das jetzt mal so gelöst. Ich denke das sollte erstmal reichen.

![Bildschirmfoto 2021-04-19 um 15 25 34](https://user-images.githubusercontent.com/8874582/115244490-45fc7680-a124-11eb-86da-b0bc82b82bc5.png)

**Comment by ottosax** [comment]
Ja, das passt so. Ich werde in den Phrasen dann auf den Sicherheitsaspekt hinweisen und später dann deine Anleitung zum Thema APIs noch verlinken. Dann hat man wohl das maximal mögliche gemacht. 👌
