### ISSUE TITLE
Nur aktive Benutzer anzeigen

### ISSUE THREAD

**Issue by cv6** [McAtze/-XT-Membermap#13]
Siehe:
Nur aktive Benutzer in der Karte anzeigen.

Nur aktiv in den letzten X Tagen.

https://xenforo.com/community/threads/xt-membermap.193479/post-1513000

**Comment by McAtze** [comment]
Macht es hier Sinn ähnlich den ignorierten Usern zu arbeiten? Also..

`/** Unset ignored user **/
            if ($userProfile->isIgnored() || !$userProfile->isRecentlyActive()) {
                unset($UserProfiles[$user_id]);
                continue;
            }`

**Comment by cv6** [comment]
Im User Finder, und gibt es die passende Funktion um das direkt in den Query miteinzubauen. 
Sonst laden wir ja je nach Forum tausende User umsonst.

	public function isRecentlyActive($days = 180)
	{
		$this->where('last_activity', '>', time() - ($days * 86400));
		return $this;
	}

Das müssen wir nun ins UserProfile übertragen. Aktuell können wir leider bei einem Finder keine where Klausel auf die Join Tabellen setzen.

Daher würde ich es aktuell so versuchen, und der Entity UserProfile eine neue Relation zu geben "RecentUser" welche wir im Listener entsprechend definieren.

		$structure->relations['RecentUser'] = [
				'entity' => 'XF:User',
				'type' => Entity::TO_ONE,
				'conditions' => [
					['user_id','=','$user_id'], 
					['last_activity', '>', time() - (18 * 86400)]
				],
				'primary' => true
			];

Dann im Repo bei der Aabfrage den With anpassen auf RecentUser und als Inner join mit true als zweitem Parameter.

    /** @return XF\Mvc\Entity\Finder **/
    public function findMapLocations()
    {
        return $this->finder('XF:UserProfile')
            ->with('RecentUser',true)
            ->keyedBy('user_id')
            ->where('xt_mm_show_on_map', '=', 1)
            ->where('xt_mm_location_lat', '<>', 0)
            ->where('xt_mm_location_long', '<>', 0);
    }

Fertig. ^^

**Comment by cv6** [comment]
Ich hab jetzt die 180 manuell eingetragen, wir müssten mal schauen wo diese Inaktivitätstage definiert werden um die selbe Quelle zu haben, Oder du baust wie Mouth es will eine eigene Zahl ein. Ich fänd das jedoch wie dort im Thema geschrieben aus UX Sicht merkwürdig, wenn auf mal bei der Karte andere Grenzwerte gelten würden, als bei den anderen Seiten.

**Comment by cv6** [comment]
Im dem Zuge sollten wir überlegen die Abfrage auf Valide User zu erweitern, analog zu dieser User Finder Funktion.

	public function isValidUser($recentlyActive = false)
	{
		$this->where('is_banned', false);
		$this->where('user_state', 'valid');
		if ($recentlyActive)
		{
			$this->isRecentlyActive();
		}
		return $this;
	}

Evtl. sollten wir doch den User Finder erweitern. So langsam brauchen wir zu viel was am User hängt.

**Comment by cv6** [comment]
Nächste mal suche ich zu Ende bevor ich schreibe. Geht doch ohne neue Relation, ich hatte nur den with Teil falsch. Also doch nur eine Anpassung an der Repo-Funktion.

    /** @return XF\Mvc\Entity\Finder **/
    public function findMapLocations($days = 180)
    {
        return $this->finder('XF:UserProfile')
            ->with('User')
            ->where('User.is_banned', false)
            ->where('User.user_state', 'valid')
            ->where('User.user_state', 'valid')
            ->where('User.last_activity', '>', time() - ($days * 86400))
            ->keyedBy('user_id')
            ->where('xt_mm_show_on_map', '=', 1)
            ->where('xt_mm_location_lat', '<>', 0)
            ->where('xt_mm_location_long', '<>', 0);
    }

**Comment by McAtze** [comment]
An der Stelle war ich auch schon. Habe aber scheinbar nicht zu Ende gedacht. Ich habe in den Where Abfrage jedesmal das User.xxx nicht korrekt gesetzt. Hatte mir schon sowas gedacht, da wir ja mit `->with('User')` die Relation schon herstellen.

**Comment by McAtze** [comment]
Wenn ich nun `public function findMapLocations($days = 180)` als Funktion nehme habe ich ja die 180 fix eingestellt. 
Verstehe ich das hier richtig, dass wenn ich dann die Funktion aufrufe als `->findMapLocations($days)` und dort per Options eine Variable `$days` übergebe, werden dann die 180 überschrieben?

**Comment by cv6** [comment]
> Wenn ich nun `public function findMapLocations($days = 180)` als Funktion nehme habe ich ja die 180 fix eingestellt.
> Verstehe ich das hier richtig, dass wenn ich dann die Funktion aufrufe als `->findMapLocations($days)` und dort per Options eine Variable `$days` übergebe, werden dann die 180 überschrieben?

Ja, die 180 ist der default Wert falls beim Aufruf nichts übergeben wird.

**Comment by McAtze** [comment]
Somit könnte ich hier noch die UserActivity als Option in die Einstellungen bringen.

**Comment by McAtze** [comment]
Ich habe das hier mal angepasst:
`
->where('User.user_state', '=', 'valid')
->where('User.is_banned', '=', 0)
`

**Comment by cv6** [comment]
> Ich habe das hier mal angepasst:
> `->where('User.user_state', '=', 'valid') ->where('User.is_banned', '=', 0)`

Wenn kein Operator angegeben ist, wird = verwendet.

**Comment by McAtze** [comment]
Ich habe gerade mal durchsucht und sehe das XF auch beide Varianten verwendet. Daher ist es scheinbar egal.
