### ISSUE TITLE
Improvements for guest views

### ISSUE THREAD

**Issue by McAtze** [McAtze/-XT-Membermap#20]
Some template changes in case that the map is allowed to view for guests.

- Set register button instead edit location
- hide the minimap widget

The other widgets can be set by the community admin per `$xf.visitor.user_id`

![Bildschirmfoto 2021-04-25 um 17 03 06](https://user-images.githubusercontent.com/8874582/115998573-206de200-a5e8-11eb-8b7f-d6148f46b411.png)

**Comment by cv6** [comment]
I think we don't need to take a special view on guests, just integrate better the permissions via 

`\XF::visitor()->canViewXtMembermap();`

So, also that field should then contain

`$xf.visitor.canViewXtMembermap()`

**Comment by McAtze** [comment]
In case of the minimap we should hide the widget for guests explicit or just show if minimap exists.

**Comment by McAtze** [comment]
I just improve the index template with:

```
<xf:if is="$xf.visitor.user_id">
	<xf:pageaction>
		<xf:button href="{{ link('account/account-details') }}" class="button--cta" fa="fa-map-marked">
			{{ phrase('xt_mm_edit_location')}}
		</xf:button>
	</xf:pageaction>
<xf:else />
	<xf:if is="$xf.options.registrationSetup.enabled">
		<xf:pageaction>
			<xf:button href="{{ link('login') }}" class="button--link button--wrap" overlay="true">
				{{ phrase('xt_mm_log_in_or_register') }}
			</xf:button>
		</xf:pageaction>
	</xf:if>	
</xf:if>
```
