### ISSUE TITLE
Änderung der Benutzergruppen eines Users -> Daten anpassen/löschen

### ISSUE THREAD

**Issue by McAtze** [McAtze/-XT-Membermap#5]

**Comment by cv6** [comment]
Erster Idee.
listener, Enitity_post_save Hint: User

Abrage auf

if ($entity->isChanged(['user_group_id', 'secondary_group_ids']))
{
  if (!$entity->canViewXtMembermap() AND $entit->Profile->xt_mm_show_on_map )
  {
    $profile = $entity->Profile;
    $profile->xt_mm_show_on_map = 0;
    $profile->xt_mm_location_lat = 0;
    $profile->xt_mm_location_long = 0;
    $profile->save();
  }
}

Das isChanged können wir auch in der anderen Funktion für Location anwenden... hab ich auch gerade erst entdeckt. Ich mag die... :)

**Comment by McAtze** [comment]
So dies funktioniert wenn ich einzelne Benutzer bearbeite, aber nicht beim Batch Update..
```
public static function entityPostSaveUser(\XF\Mvc\Entity\Entity $entity)
	{
		if ($entity->isChanged(['user_group_id', 'secondary_group_ids']))
		{
			if (!$entity->canViewXtMembermap() AND $entity->Profile->xt_mm_show_on_map)
			{
				$profile = $entity->Profile;
				$profile->xt_mm_show_on_map = 0;
				$profile->xt_mm_location_lat = 0;
				$profile->xt_mm_location_long = 0;
				$profile->save();
			}
		}

		if ($entity->isStateChanged('user_state', 'disabled') === 'enter')
		{
			if (!$entity->canViewXtMembermap() AND $entity->Profile->xt_mm_show_on_map)
			{
				$profile = $entity->Profile;
				$profile->xt_mm_show_on_map = 0;
				$profile->xt_mm_location_lat = 0;
				$profile->xt_mm_location_long = 0;
				$profile->save();
			}
		}
	}
```

**Comment by cv6** [comment]
Jedesmal wenn wir die Daten entfernen wiederholen wir Code. Evtl. macht es Sinn alle Stelle die so aussehen in einer Entity Funktion zusammenzufassen. z.B. Also in der UserProfile Entity.

```
public function removeLocationData($save = false)
{
    $this->xt_mm_show_on_map = 0;
    $this->xt_mm_location_lat = 0;
    $this->xt_mm_location_long = 0;
    if ($save)
    {
        $this->save();
    }
}
```

**Comment by McAtze** [comment]
Das macht auf jeden Fall Sinn. Baue ich dann mal um.

**Comment by McAtze** [comment]
Macht es dann nicht auch Sinn direkt noch ein `$entity->removeMinimapIfExists();` mit einzubauen?
Also...
```
public static function entityPostSaveUser(\XF\Mvc\Entity\Entity $entity)
{
    if ($entity->isChanged(['user_group_id', 'secondary_group_ids']))
    {
        if (!$entity->canViewXtMembermap() AND $entity->Profile->xt_mm_show_on_map)
        {
            $entity->Profile->removeLocationData(true);
            $entity->removeMinimapIfExists();
        }
    }

    if ($entity->isStateChanged('user_state', 'disabled') === 'enter')
    {
        if (!$entity->canViewXtMembermap() AND $entity->Profile->xt_mm_show_on_map)
        {
            $entity->Profile->removeLocationData(true);
            $entity->removeMinimapIfExists();
        }
    }
}
```

**Comment by cv6** [comment]
Ja, eigentlich gehört das sogar mit in die removeLocationData Funktion. Wenn wir die Daten entfernen sollte die auch weg sein.

**Comment by McAtze** [comment]
In RC 3 integriert => Wenn Benutzergruppe geändert wird, werden Berechtigungen geprüft und ggf. Minimap gelöscht und xt_mm_** rows in DB geleert.
