### ISSUE TITLE
User löschen -> Minimap löschen

### ISSUE THREAD

**Issue by McAtze** [McAtze/-XT-Membermap#6]

**Comment by McAtze** [comment]
@cv6 ich habe bisher keinen Ansatz gefunden wo ich hier das `removeMinimapIfExist()` anbringen kann.

Das wäre noch so ein Punkt der für die RC3 wichtig wäre. Könntest du hier mir einen Hinweis geben?

**Comment by cv6** [comment]
einen Listener für das Code Event _entity_post_delete_  als Hint die Entity des Users angeben.
    public static function entityPostDeleteUser(\XF\Service\User\DeleteCleanUp $deleteService, array &$deletes)
    {
        $entity->removeMinimapIfExist()
    }

**Comment by McAtze** [comment]
Und es kann so einfach sein... 

```
public function _postDelete()
  {
    return $this->removeMinimapIfExists();
  }
```

**Comment by cv6** [comment]
Das funktioniert leider aus zwei Gründen nicht.
Wenn du Funktionen überschreibst, musst du die auf jeden Fall **parent::FunktionsName()** mit einbauen. da sonst die Original Methode nicht aufgerufen wird.
Aber, und das ist an dieser Stelle entscheidend, sind die _postDelete() Methode vom Typ _protected_.

Daher geht nur der Weg den ich geschrieben habe, denn genau in der Methode wird der Event gefeuert und der Listener wird dann ausgeführt.

**Comment by McAtze** [comment]
Jetzt bin ich aber etwas verwirrt. Dein Einwand verstehe ich durchaus, aber dies hat gerade genauso funktioniert.

Auch wenn ich dies so umsetzt funktioniert dies:
```
protected function _postDelete()
{
 parent::_postDelete();
 return $this->removeMinimapIfExists();
}
```

Ich habe auch den Weg von dir über den Listener ausprobiert und bin am Entity hängengeblieben. Der kam immer als Fehler das dieser nicht eingebunden werden konnte.

**Comment by McAtze** [comment]
Selbst XF extended im XFES die Post class mit der protected function _postSave()
```
class Post extends XFCP_Post
{
	protected function _postSave()
	{
		parent::_postSave();

		if (
			$this->isFirstPost() &&
			$this->isUpdate() &&
			$this->isChanged('message')
		)
		{
			$this->db()->delete(
				'xf_es_thread_similar',
				'thread_id = ?',
				$this->thread_id
			);
		}
	}
}
```

**Comment by cv6** [comment]
Na dann.... da wir die Entity extended haben.

**Comment by McAtze** [comment]
Ich bin jetzt immer wieder darüber gestolpert das lieber mit dem Listener gearbeitet werden soll als die Klassen zu extenden.
Was wäre denn nun die bessere Variante oder die saubere Lösung?

**Comment by cv6** [comment]
Steht ja auch so in den Coding standards von XF.

Code Listener sind immer vorzuziehen, da sie robuster sind. Beim Extenden kann viel schieflaufen, vor allem wenn man viele AddOns hat läuft man Gefahr sich in die Quere zu kommen. Gerade bei so wichtigen Funktionen. 

Mein Beispiel oben hat aber auch die falschen Parameter. Die Signatur wird im ACP beim erstellen vorgegeben.

![image](https://user-images.githubusercontent.com/1529415/115599485-f6f94180-a2db-11eb-9816-189c7710f31e.png)

	public static function entityPostDeleteUser(\XF\Mvc\Entity\Entity $entity)
	{
		$entity->removeMinimapIfExist();
	}

Ungetestet, sollte aber so funktionieren.

**Comment by McAtze** [comment]
Jup, das läuft und ich verstehen jetzt auch was du meinst mit dem Listener. Danke dir nochmals für die Geduld.

**Comment by cv6** [comment]
Kein Problem. Rechnung kommt. ^^
