### ISSUE TITLE
User verbannen (sollte mit Änderung der Gruppe passieren, prüfen.)

### ISSUE THREAD

**Issue by McAtze** [McAtze/-XT-Membermap#7]

**Comment by McAtze** [comment]
Dürfte sich hiermit erledigt habe: https://github.com/McAtze/-XT-Membermap/issues/13

**Comment by cv6** [comment]
Ähnlich der anderen Funktion. Können wir vermutlich in einem Listener abbilden.

if ($this->isStateChanged('user_state', 'valid') === 'leave')
{
  if (!$entity->canViewXtMembermap() AND $entit->Profile->xt_mm_show_on_map )
  {
    $profile = $entity->Profile;
    $profile->xt_mm_show_on_map = 0;
    $profile->xt_mm_location_lat = 0;
    $profile->xt_mm_location_long = 0;
    $profile->save();
  }
}

**Comment by McAtze** [comment]
Wie auch hier (https://github.com/McAtze/-XT-Membermap/issues/5#issuecomment-824895197) funktioniert dies nur wenn einzelne Nutzer bearbeitet werden.

**Comment by McAtze** [comment]
Die Variante wenn ein User gebannt wurde ist etwas tricky. Ich bekomme die Minimap gelöscht, aber die Einträge aus der DB nicht weg. Ich habe mich mal wie folgt versucht.

1. Neue Funktion:
```
public static function entityPostSaveUserBan(\XF\Mvc\Entity\Entity $entity)
	{
		$user = $entity->User;
		
		$user->removeLocationData(true);
	}
```
2.  Event Listener angelegt mit Hint: XF\Entity\UserBan

Es will nicht so wie ich will.

**Comment by cv6** [comment]
Die Funktion ist im Profil.

$entity->Profile->removeLocationData(true);

**Comment by McAtze** [comment]
Die Funktion ist in `XT\Membermap\XF\Entity\User.php`

```
    public function removeLocationData($save = false)
    {
        $this->Profile->xt_mm_show_on_map = 0;
        $this->Profile->xt_mm_location_lat = 0;
        $this->Profile->xt_mm_location_long = 0;
        if ($save)
        {
			$this->removeMinimapIfExists();
            $this->save();
        }
    }
```



Was mich wundert ist das die Minimap gelöscht wird, aber die DB nicht.

**Comment by cv6** [comment]
Ah ja, richtig.
Weil wir den User speichern, und nicht das Profil. Vermutlich klappte das bei dem anderen weil da auch das Profil verändert wird. 
$this->Profile->save();

**Comment by McAtze** [comment]
Jetzt funktioniert alles.. 👍 

```
public static function entityPostSaveUserBan(\XF\Mvc\Entity\Entity $entity)
{
    $user = $entity->User;		
    $user->removeLocationData(true);
    $user->Profile->save();
}
```

**Comment by cv6** [comment]
Ich meinte in der removeLocationData funktion ist das save falsch. Da soll nicht der User gespeichert werden, das kann zu Fehlern führen. Da das Profile mit reinnehmen.

**Comment by McAtze** [comment]
Alles klar. Also das Thema können wir abschließen.

In RC3 integriert => Wenn User gebannt, dann lösche Minimap und leere xt_mm_*** rows in DB.
